[tool.poetry]
name = "fastapi-control"
version = "0.4.0"
description = "FastAPI utility to implement class-based routing with controllers and dependency injection."
authors = ["Leynier Gutiérrez González <leynier41@gmail.com>"]
homepage = "https://github.com/leynier/fastapi-control"
repository = "https://github.com/leynier/fastapi-control"
documentation = "https://github.com/leynier/fastapi-control"
readme = "README.md"
license = "MIT"

[tool.poetry.dependencies]
python = "^3.10"
fastapi = ">=0.141.1,<2.0.0"
kink = ">=0.9.0,<0.10.0"

[tool.poetry.group.dev.dependencies]
fastapi = {extras = ["all"], version = ">=0.141.1,<2.0.0"}
pytest = ">=9.1.1,<10.0.0"
pytest-cov = "^7.1.0"
pytest-asyncio = "^1.4.0"
black = "^26.5.1"
flake8 = "^7.3.0"
isort = "^8.0.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
